from __future__ import annotations

from typing import Any


_SEVERITY_ICONS = {
    "critical": "🔴",
    "error": "🟠",
    "warning": "🟡",
    "info": "🔵",
}


def format_pr_comment(result: dict[str, Any]) -> str:
    """Format workflow results as a GitHub PR comment in Markdown."""
    sections: list[str] = []

    sections.append("## 🤖 DevPilot AI — Codebase Intelligence Report\n")

    # ── Code Understanding ──
    understanding = result.get("code_understanding")
    if understanding:
        sections.append(
            "<details>\n<summary><strong>📖 Code Understanding</strong></summary>\n"
        )
        sections.append(f"**Summary:** {understanding.get('summary', 'N/A')}\n")

        details = understanding.get("details", [])
        if details:
            sections.append("**Details:**")
            for detail in details:
                sections.append(f"- {detail}")

        impact = understanding.get("impact", "")
        if impact:
            sections.append(f"\n**Impact:** {impact}")

        sections.append("\n</details>\n")

    # ── Test Suggestions ──
    tests = result.get("test_suggestions", [])
    if tests:
        sections.append(
            f"<details>\n<summary><strong>🧪 Test Suggestions ({len(tests)})</strong></summary>\n"
        )
        for test in tests:
            test_type = test.get("test_type", "unknown").upper()
            desc = test.get("description", "")
            file_name = test.get("file_name", "")
            code = test.get("code", "")

            sections.append(f"### [{test_type}] {file_name}")
            if desc:
                sections.append(f"_{desc}_\n")

            lang = "javascript" if test_type == "K6" else "python"
            sections.append(f"```{lang}\n{code}\n```\n")

        sections.append("</details>\n")

    # ── Documentation Updates ──
    docs = result.get("documentation_updates", [])
    if docs:
        sections.append(
            f"<details>\n<summary><strong>📝 Documentation Updates ({len(docs)})</strong></summary>\n"
        )
        for doc in docs:
            action = doc.get("action", "update").upper()
            section_name = doc.get("section", "Unknown")
            content = doc.get("content", "")

            sections.append(f"### [{action}] {section_name}")
            sections.append(f"{content}\n")

        sections.append("</details>\n")

    # ── Review Findings ──
    findings = result.get("review_findings", [])
    if findings:
        # Sort by severity
        severity_order = {"critical": 0, "error": 1, "warning": 2, "info": 3}
        findings_sorted = sorted(
            findings,
            key=lambda f: severity_order.get(f.get("severity", "info"), 4),
        )

        sections.append(
            f"<details open>\n<summary><strong>🔍 Code Review ({len(findings)})</strong></summary>\n"
        )

        sections.append("| Severity | Category | Location | Finding |")
        sections.append("|----------|----------|----------|---------|")

        for finding in findings_sorted:
            sev = finding.get("severity", "info")
            icon = _SEVERITY_ICONS.get(sev, "⚪")
            cat = finding.get("category", "general")
            fp = finding.get("file_path", "")
            line = finding.get("line")
            msg = finding.get("message", "")
            suggestion = finding.get("suggestion", "")

            location = fp
            if line:
                location += f"#L{line}"

            full_msg = msg
            if suggestion:
                full_msg += f" **Fix:** {suggestion}"

            sections.append(f"| {icon} {sev} | {cat} | `{location}` | {full_msg} |")

        sections.append("\n</details>\n")

    # ── Errors ──
    errors = result.get("errors", [])
    if errors:
        sections.append("<details>\n<summary>⚠️ Processing Errors</summary>\n")
        for err in errors:
            sections.append(f"- {err}")
        sections.append("\n</details>\n")

    sections.append("---\n_Generated by DevPilot AI_")

    return "\n".join(sections)


def format_json_response(result: dict[str, Any]) -> dict[str, Any]:
    """Format workflow result into a structured JSON response."""
    return {
        "repo": result.get("repo", ""),
        "branch": result.get("branch", ""),
        "changed_files": [
            f.get("filename", "") for f in result.get("changed_files", [])
        ],
        "code_understanding": result.get("code_understanding"),
        "test_suggestions": result.get("test_suggestions", []),
        "documentation_updates": result.get("documentation_updates", []),
        "review_findings": result.get("review_findings", []),
        "errors": result.get("errors", []),
    }
